### ISSUE TITLE
TCG consecutive win count doesn't save.

### ISSUE THREAD

**Issue by tamixy** [JianmengYu/ElonaPlusCustom-GX#21]
TCG takes quite a bit of time, so getting to 5 wins in a single session to get a card pack and higher number of music tickets means I would need to pretty much do just TCG the whole time. Seems important to save the win count between game sessions.

**Comment by JianmengYu** [comment]
The ticket rewards was added more as a little incentive than the main source of music tickets.
Acquiring tickets through Party Time quests should be much faster.
Anyways it's now saved in 2.23.1.1.
