### ISSUE TITLE
CTD when using special action 'Continuous Attacks'

### ISSUE THREAD

**Issue by Velossy** [JianmengYu/ElonaPlusCustom-GX#22]
This issue is present when using the special action 'Continuous Attacks' on an enemy, provided the enemy is strong enough to live through most of the attack where midway through the CTD occurs. It is replicable every time, and has been present in CGX since version 2.22 was released, but is not present in 2.21 (I was able to test since having my older install folders still on my PC). It does not occur in any version of normal Elona+.

Here is the crash log:

HspError 19 WinError 1400 Line -1 Ver 6330 Mode 0
Message (JP): 0‚ÅœŽZ‚µ‚Ü‚µ‚½
Message (EN): Divided by zero
efId 697 efP 170 Area 13/1
ci 28#19 ti 0#1114 cc 0#0 tc 64#1049 rc 82#16
7. ctrlFile:game0:16 ct:0
6. ctrlFile:game0:17 ct:0
5. ctrlFile:game0:18 ct:0
4. ctrlFile:game0:logs ct:0
3. ctrlFile:game0:array ct:0
2. ctrlFile:game0:evs ct:0
1. ctrlFile:game0:end ct:0
0. ctrlFilegdatan/end ct:0

Please check and organize the information as to what kind of thing you were doing when the error occurred, if it is reproducible, screenshot showing the problem, comparison of the results from the vanilla version. In addition, if you can use the bug reporting template on the Elona board development thread, it would help identify the cause and will be saved for reference. There is little chance it will be solved if you provide very little information or just the error code.

**Comment by JianmengYu** [comment]
Fixed in 1096df7
