### ISSUE TITLE
Can't complete Destiny ( It gets stuck on the Y )

### ISSUE THREAD

**Issue by popopop1279** [JianmengYu/ElonaPlusCustom-GX#24]
Hello! I've recently gotten back into playing, and was trying to complete Destiny but it seems that it's gotten stuck on the Y for some reason. I asked on the discord server and it doesn't seem like it's a issue with E+ so I think something with this might have broken it. It's stuck on the last Y, and hasn't completed no matter how many times I sleep or complete dungeons.

**Comment by JianmengYu** [comment]
If you had disabled DESTINY in an earlier version, that may cause the progress to be stuck.
Disable DESTINY (This should reset progress now) and enable DESTINY again.

Just tested and confirmed it works in 2.24.2.1, you could use the following step to test:
Travel for skill exp to get 5 letters. If you disabled study days this wont happen.
F12+Wizard+F6 speed up time to sleep 3 times.
Clear a RANDOM nefia. make sure you kill the boss and not escape early.

**Comment by popopop1279** [comment]
I'll give it a try rn, ty for the response
