### ISSUE TITLE
Autopickup does not function in japanese language

### ISSUE THREAD

**Issue by Itzpalt** [JianmengYu/ElonaPlusCustom-GX#6]
Autopickup seems to work fine in english, but I cannot get it to do anything at all under japanese.
I activate it from the extra settings, I have the "自動拾い" status, and I reload the autopick.txt with shift-backspace, and elona reports that it has reloaded (autopick.txtを最読み込みした。).
However, nothing happens when I walk over the designated items.

To reproduce:
Create a autopick.txt containing:
bottle of water?
水?

Set the game's language to english, enable autopick, and drop a bottle of water.
Walk over it on english, you will be prompted to pick it up.
Change language to japanese, restart the game.
Walk over it on japanese, nothing happens.

Tested in wine and on native Windows 10

**Comment by JianmengYu** [comment]
![image](https://github.com/JianmengYu/ElonaPlusCustom-GX/assets/20024019/d62ebe38-452f-4e45-be97-7e912093bf27)
![image](https://github.com/JianmengYu/ElonaPlusCustom-GX/assets/20024019/2ac19c3b-3f47-44f4-b07e-0357a4e67344)
It works for me, make sure the autopick.txt is saved in `shift-JIS`

**Comment by Itzpalt** [comment]
Fixing the encoding got it working, I had to change the line encoding from "Unix/Linux" to "Windows" as well.
![image](https://github.com/JianmengYu/ElonaPlusCustom-GX/assets/61453805/929d16ce-64b3-49b5-a6e5-2ad41b6d1f93)
