### ISSUE TITLE
Not sure if it has to do with the file or what but I am getting a "zip file cannot open as archive" error?

### ISSUE THREAD

**Issue by Ryan7251** [JianmengYu/ElonaPlusCustom-GX#7]
Ok so I wanted to update my game but when I try to unzip I get a cannot open file as archive error not sure if it's on my side or not but just wanted to bring it up if by chance it's not.

**Comment by JianmengYu** [comment]
It's openable for me.
MD5 Checksum: e6f1a4b37551af6819569b05c0aef540

Windows> `CertUtil -hashfile Elona+.Custom-GX.2.21.3.0.zip MD5`
Linux$ `md5sum Elona+.Custom-GX.2.21.3.0.zip`

**Comment by Ryan7251** [comment]
I managed to fix the issue it was on my side namely my internet was stopping it since it is not commonly downloaded just switched to windows 11 and I guess that is a thing now?

anyway my bad
